models/Titulo.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "titulo".
 *
 * @property integer $id
 * @property string $nome
 * @property integer $idCategoria
 *
 * @property Arquivo[] $arquivos
 * @property Subtitulo[] $subtitulos
 * @property Categoria $idCategoria0
 */
class Titulo extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'titulo';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['nome', 'idCategoria'], 'required'],
            [['idCategoria'], 'integer'],
            [['nome'], 'string', 'max' => 255],
            [['idCategoria'], 'exist', 'skipOnError' => true, 'targetClass' => Categoria::className(), 'targetAttribute' => ['idCategoria' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'nome' => 'Nome',
            'idCategoria' => 'Categoria',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArquivos() {
        return $this->hasMany(Arquivo::className(), ['idTitulo' => 'id', 'idCategoria' => 'idCategoria']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubtitulos() {
        return $this->hasMany(Subtitulo::className(), ['idTitulo' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategoria() {
        return $this->hasOne(Categoria::className(), ['id' => 'idCategoria']);
    }

}

controllers/SubtituloController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Subtitulo;
use app\models\SubtituloSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SubtituloController implements the CRUD actions for Subtitulo model.
 */
class SubtituloController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Subtitulo models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new SubtituloSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Subtitulo model.
     * @param integer $id
     * @param integer $idTitulo
     * @return mixed
     */
    public function actionView($id, $idTitulo) {
        return $this->render('view', [
                    'model' => $this->findModel($id, $idTitulo),
        ]);
    }

    /**
     * Creates a new Subtitulo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Subtitulo();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id, 'idTitulo' => $model->idTitulo]);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Subtitulo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @param integer $idTitulo
     * @return mixed
     */
    public function actionUpdate($id, $idTitulo) {
        $model = $this->findModel($id, $idTitulo);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id, 'idTitulo' => $model->idTitulo]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Subtitulo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @param integer $idTitulo
     * @return mixed
     */
    public function actionDelete($id, $idTitulo) {
        $this->findModel($id, $idTitulo)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Subtitulo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @param integer $idTitulo
     * @return Subtitulo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, $idTitulo) {
        if (($model = Subtitulo::findOne(['id' => $id, 'idTitulo' => $idTitulo])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

controllers/TituloController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Titulo;
use app\models\TituloSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TituloController implements the CRUD actions for Titulo model.
 */
class TituloController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Titulo models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new TituloSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Titulo model.
     * @param integer $id
     * @param integer $idCategoria
     * @return mixed
     */
    public function actionView($id, $idCategoria) {
        return $this->render('view', [
                    'model' => $this->findModel($id, $idCategoria),
        ]);
    }

    /**
     * Creates a new Titulo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Titulo();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'id' => $model->id, 'idCategoria' => $model->idCategoria]);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Titulo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @param integer $idCategoria
     * @return mixed
     */
    public function actionUpdate($id, $idCategoria) {
        $model = $this->findModel($id, $idCategoria);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id, 'idCategoria' => $model->idCategoria]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Titulo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @param integer $idCategoria
     * @return mixed
     */
    public function actionDelete($id, $idCategoria) {
        $this->findModel($id, $idCategoria)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Titulo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @param integer $idCategoria
     * @return Titulo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, $idCategoria) {
        if (($model = Titulo::findOne(['id' => $id, 'idCategoria' => $idCategoria])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

views/titulo/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use \yii\helpers\ArrayHelper;
use app\models\Categoria;

/* @var $this yii\web\View */
/* @var $model app\models\Titulo */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="titulo-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nome')->textInput(['maxlength' => true]) ?>

    <?=
    $form->field($model, 'idCategoria')->dropDownList(
            ArrayHelper::map(Categoria::find()->all(), 'id', 'nome'), ['prompt'=>'Selecione a Categoria']
    )
    ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Salvar' : 'Atualizar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/titulo/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TituloSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="titulo-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nome') ?>

    <?= $form->field($model, 'idCategoria') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/titulo/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Titulo */

$this->title = 'Novo Titulo';
$this->params['breadcrumbs'][] = ['label' => 'Titulos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="titulo-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
    ])
    ?>

</div>

views/titulo/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TituloSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Titulos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="titulo-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Novo Título', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Novo Subtítulo', ['subtitulo/create'], ['class' => 'btn btn-info']) ?>
    </p>
    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'], //mosta número de linhas da coluna da Tabela          
//            'id',
            'nome',
            [
                'attribute' => 'idCategoria',
                'value' => 'categoria.nome'
            ],
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]);
    ?>
</div>

views/titulo/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Titulo */

$this->title = 'Update Título: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Títulos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id, 'idCategoria' => $model->idCategoria]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="titulo-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/titulo/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Titulo */

$this->title = "Sistema Gerenciador de HQ's";
$this->params['breadcrumbs'][] = ['label' => 'Titulos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="titulo-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Novo Título', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Atualizar', ['update', 'id' => $model->id, 'idCategoria' => $model->idCategoria], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Deletar', ['delete', 'id' => $model->id, 'idCategoria' => $model->idCategoria], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Você tem certeza que deseja remover esse item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nome',
            'categoria.nome',
        ],
    ]) ?>

</div>